version: '3.0'

networks:
  keazy_network:
    driver: bridge

services:

  redis:
      image: redis:latest
      container_name: redis
      ports:
        - "6380:6379"
      networks:
        - keazy_network
      restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/ssl/nginx.crt:/etc/nginx/ssl/nginx.crt:rw
      - ./nginx/ssl/nginx.key:/etc/nginx/ssl/nginx.key:rw
    networks:
      - keazy_network
    depends_on:
      - web
    restart: always

  web:
    build:
      context: ./web
    container_name: keazy_web
    volumes:
      - web_volume:/app
      - static_volume:/app/static
    networks:
      - keazy_network
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    container_name: keazy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keazydb
      POSTGRES_USER: keazyuser
      POSTGRES_PASSWORD: keazypassword
    networks:
      - keazy_network
    restart: always

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/debian/main/keazy/srcs/db/data

  static_volume:

  web_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/debian/main/keazy/srcs/web/src
